/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;

    char temp[255];
    
	for (int i = 0, j =0 ; i < strlen(argp->wartosc); i++, j += 2){
        sprintf((char*)result.wynik+j,"%02X",argp->wartosc[i]);
    }
    
    
	return &result;
}
